# SPDX-FileCopyrightText: 2026 ORDeC contributors
# SPDX-License-Identifier: Apache-2.0

import os
from pathlib import Path

import pytest

from ordec.core import *
from ordec.extlibrary import ExtLibrary
from ordec.lib import ihp130
from ordec.schematic.spice_in import clean_cards, tokenize, parse_deck, SpiceImportError

stdcell_root = ihp130.pdk().root / "libs.ref/sg13g2_stdcell"
stdcell_spice = stdcell_root / "spice/sg13g2_stdcell.spice"
stdcell_lef = stdcell_root / "lef/sg13g2_stdcell.lef"


# Stage A: preprocessing (comments + continuations)
# -------------------------------------------------

def test_continuation_stitching():
    cards = clean_cards("M1 d g s b nch\n+ w=1u l=1u\n+ m=2")
    assert cards == ["M1 d g s b nch w=1u l=1u m=2"]


def test_full_line_comments():
    text = "* star comment\n# hash comment\n$ dollar comment\nR1 a b 1k"
    assert clean_cards(text) == ["R1 a b 1k"]


def test_inline_comments():
    assert clean_cards("R1 a b 1k ; trailing") == ["R1 a b 1k"]
    assert clean_cards("R1 a b 1k // trailing") == ["R1 a b 1k"]
    assert clean_cards("R1 a b 1k $ trailing") == ["R1 a b 1k"]
    # A leading ';' makes the whole line a comment (no card emitted).
    assert clean_cards("; whole line") == []


def test_comment_chars_inside_quotes_not_stripped():
    card = clean_cards("B1 o 0 V='a;b' extra")[0]
    assert "a;b" in card


# Stage B: tokenizer + parsing
# ----------------------------

def testtokenize_keeps_brace_and_quote_groups():
    toks = tokenize("B1 o 0 V={a + b; c} I='x y'")
    assert toks == ["B1", "o", "0", "V={a + b; c}", "I='x y'"]


def test_parse_deck_instance_and_params():
    deck = parse_deck(
        ".subckt myinv Y A VDD VSS\n"
        "XN0 Y A VSS VSS sg13_lv_nmos w=740.00n l=130.00n ng=1 m=1\n"
        ".ends\n"
    )
    assert list(deck.subckts) == ["myinv"]
    sub = deck.subckts["myinv"]
    assert sub.ports == ["Y", "A", "VDD", "VSS"]
    assert len(sub.instances) == 1
    inst = sub.instances[0]
    assert inst.name == "XN0" and inst.prefix == "X"
    assert inst.nodes == ["Y", "A", "VSS", "VSS"]
    assert inst.model == "sg13_lv_nmos"
    assert inst.params["w"] == "740.00n" and inst.params["ng"] == "1"


def test_parse_subckt_header_params():
    deck = parse_deck(".subckt foo a b params: x=1 y=2\n.ends\n")
    sub = deck.subckts["foo"]
    assert sub.ports == ["a", "b"]
    assert sub.params == {"x": "1", "y": "2"}


def test_parse_real_stdcell_file():
    deck = parse_deck(stdcell_spice.read_text())
    assert len(deck.subckts) == 84
    inv = deck.subckts["sg13g2_inv_1"]
    assert inv.ports == ["Y", "A", "VDD", "VSS"]
    assert len(inv.instances) == 2
    assert {i.model for i in inv.instances} == {"sg13_lv_nmos", "sg13_lv_pmos"}


# Schematic construction
# ----------------------

def test_build_schematic_standalone_auto_symbol():
    lib = ExtLibrary()
    lib.read_spice(stdcell_spice, device_map=ihp130.device_map)

    # Auto-generated symbol matches the subckt port list.
    sym = lib["sg13g2_inv_1"].symbol
    assert {p.full_path_str() for p in sym.all(Pin)} == {"A", "Y", "VDD", "VSS"}

    sch = lib["sg13g2_inv_1"].schematic
    insts = list(sch.all(SchemInstance))
    assert len(insts) == 2
    cells = {type(i.symbol.cell).__name__ for i in insts}
    assert cells == {"Nmos", "Pmos"}
    # Parameter mapping: l/w as R, ng/m as int; ad/as/pd/ps dropped.
    nmos = next(i.symbol.cell for i in insts if type(i.symbol.cell).__name__ == "Nmos")
    assert nmos.l == R("130n") and nmos.w == R("740n")
    assert nmos.ng == 1 and nmos.m == 1


def test_build_larger_cell():
    lib = ExtLibrary()
    lib.read_spice(stdcell_spice, device_map=ihp130.device_map)
    sch = lib["sg13g2_dfrbp_1"].schematic
    assert len(list(sch.all(SchemInstance))) == 34


def test_lef_symbol_wins_over_autogenerated():
    lib = ExtLibrary()
    lib.read_lef(stdcell_lef)
    lib.read_spice(stdcell_spice, device_map=ihp130.device_map)

    sym = lib["sg13g2_inv_1"].symbol
    # Pin directions come from LEF, not the Inout auto-symbol fallback.
    assert sym.A.pintype == PinType.In
    assert sym.Y.pintype == PinType.Out

    sch = lib["sg13g2_inv_1"].schematic
    assert sch.Y.pin.pintype == PinType.Out
    assert len(list(sch.all(SchemInstance))) == 2


def test_unknown_model_raises(tmp_path):
    netlist = tmp_path / "bad.spice"
    netlist.write_text(".subckt bad a b\nX0 a b mysterydev\n.ends\n")
    lib = ExtLibrary()
    lib.read_spice(netlist, device_map=ihp130.device_map)
    with pytest.raises(SpiceImportError, match="mysterydev"):
        lib["bad"].schematic


def test_duplicate_schematic_source_raises(tmp_path):
    from ordec.extlibrary import ExtLibraryError
    netlist = tmp_path / "dup.spice"
    netlist.write_text(".subckt dup a b\n.ends\n")
    lib = ExtLibrary()
    lib.read_spice(netlist, device_map=ihp130.device_map)
    with pytest.raises(ExtLibraryError, match="dup"):
        lib.read_spice(netlist, device_map=ihp130.device_map)
